/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_drillinginfo_global_test_utils_ImagesComparer */

#ifndef _Included_com_drillinginfo_global_test_utils_ImagesComparer
#define _Included_com_drillinginfo_global_test_utils_ImagesComparer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_drillinginfo_global_test_utils_ImagesComparer
 * Method:    compare
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_drillinginfo_global_test_utils_ImagesComparer_compare
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
